# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec4a9020e344dc5ef393f95921045f6888a0f7219f13df5d05dc3403d7c24448ef96bd6ca18aa35082283dcf77406f29a4d4da74399bd61466ce9db5219b630

test:
  secret_key_base: e986904d7d70c8d94b039efc54c403d5d7977f86e3d84eba9aa40be69606c35f5447646a85c3ea72e07646cabd7d969d0dc0655417ceddd83cb7f888399bf8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
